### ISSUE TITLE
Progress information?

### ISSUE THREAD

**Issue by larskotthoff** [marlam/msmtp-mirror#108]
Would it be possible to show progress information when sending, e.g. a progress bar or number of bytes sent? I'm using msmtp from a web frontend, and when sending large mails or over slow connections, the web server sometimes kills the process as it appears frozen.

Thanks!

**Comment by marlam** [comment]
Msmtp does not write to standard output because it may be called by programs that expect it to be quiet. Also, it does not know how large the input is because it acts as a pipe only: it reads input bytes as they are available and forwards them to the SMTP server.
And that might be the cause of your problem: For example, a long-running cron job might take very long to produce output, triggering an SMTP server timeout. To work around this, first buffer the output of the job to some file, then send this file via msmtp.

**Comment by larskotthoff** [comment]
Thanks -- would it be possible to output a running total of the number of bytes piped, for example? And only if a flag is given.

**Comment by marlam** [comment]
That would be possible, but you can probably achieve the same thing with [pv](https://www.ivarch.com/programs/pv.shtml).

**Comment by larskotthoff** [comment]
Ah! Yes, you're right. This will work and won't require support from msmtp. I'll close this, thanks!

**Comment by edi9999** [comment]
Do you know how you should use pv together with msmtp ?

**Comment by marlam** [comment]
```
pv mymail.txt | msmtp ...
```

or, when piping

```
mailoutputprog | pv | msmtp ...
```

**Comment by edi9999** [comment]
Thank you marlam, it is working well.

In my case msmtp is run inside a script and, if it could be used for someone, here is the portion of the script :


```
pv --format "%p %e" --force <"$mail/message" 2> >(tee /tmp/msmtp_progress.log) |
		xargs -0 -a "$mail/msmtp_flags" msmtp --debug -C "$CONFIG" -X -
```

I use xargs because the message itself is stored in a file, and the flags are stored in another file.

The /tmp/msmtp_progress.log is then read by my i3bar like this : 

```
if [ -f /tmp/msmtp_progress.log ]; then
    mail_pct=" $(
        cat </tmp/msmtp_progress.log -A |
            sed -r -e "s@([^^]+)\^M@\1\n@g" |
            sed -r "s@.*[^0-9]([0-9%]+ ETA [0-9:]+)@\1@g" |
            tail -n 1
    )"
fi
```
