### ISSUE TITLE
Feature Request: Support Opportunistic TLS

### ISSUE THREAD

**Issue by alowther** [marlam/msmtp-mirror#114]
Opportunistic TLS would use TLS if available, but send in the clear if TLS is not available.

I use `mstmp` to send mail via a smarthost.  We enable TLS using the settings
```
tls on
tls_starttls on
tls_certcheck off
```
This usually works fine, but sometimes the TLS settings on the smarthost are wrong and mail fails to deliver.  I would prefer to send the email without TLS than to have the email fail.

I have used Opportunistic TLS with Postfix using the settings
```
smtp_tls_security_level = may
smtp_tls_note_starttls_offer = yes
```
Here is the Postfix documentation on Opportunistic TLS https://www.postfix.org/TLS_README.html#client_tls_may

**Comment by marlam** [comment]
Msmtp only talks to a single configured SMTP server per account and therefore knows the correct TLS settings for this server.

If for a given SMTP server TLS only works sometimes, then it seems likely that something nefarious is going on (a man-in-the-middle attack like command injection or STARTTLS stripping), and in this case you absolutely want msmtp to abort instead of falling back to plaintext.

Opportunistic TLS in postfix only makes sense since postfix does not know in advance with which SMTP servers it will speak and whether they support TLS or not. This problem is addressed by [DANE](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities) (which is unfortunately not universally available yet).

Also, please don't use `tls_certcheck off`. You're disabling the advantages that TLS has to offer.

**Comment by alowther** [comment]
It is not nefarious when the mail admin for the SMTP server forgets to renew the certificate.  The point is that there are situations when the TLS settings of the server will break for ordinary reasons and I would not want msmtp to abort.

**Comment by marlam** [comment]
I disagree: if you offer TLS, you commit to it, and there are no acceptable/ordinary reasons why it would not work. Otherwise you are not offering the safety guarantees that TLS provides. How would a client be able to tell the difference between a broken configuration, an ongoing attack or a forgetful admin?

Today, there is really no excuse for having broken TLS configurations.

I'm sorry, but a plaintext fallback will not be implemented in msmtp. That would do more harm than good.

**Comment by alowther** [comment]
I appreciate the comments.  I'll share my final thoughts for completeness.

If msmtp has the setting `tls on` and there is a broken TLS configuration then msmtp will fail to send an email and that email is lost forever.  Please correct me if I am wrong, but there is no queueing option in msmtp to store and retry emails until the TLS configuration is fixed.

It would be completely reasonable for my users to insist on the most reliable msmtp configuration to make sure no email is lost.  In that situation I would have to set `tls off`.  I think Opportunistic TLS is preferable to no TLS.

> How would a client be able to tell the difference between a broken configuration, an ongoing attack or a forgetful admin?
It can't.  Opportunistic TLS would provide another way to configure msmtp on how to handle the situation.

> there is really no excuse for having broken TLS configurations
This is a nice idea, but stuff still happens.  As previously mentioned, msmtp has the option `tls_certcheck off` even though it is discouraged.  The option is still available though, and I would think part of the reasoning is because broken TLS is preferable to no TLS or to having the email be lost.

> plaintext fallback ... would do more harm than good
I do not see why.  It would not be required.  msmtp could still be configured to require tls.

**Comment by marlam** [comment]
I agree that losing a mail because of some failure (be it TLS or DNS or network hiccups of any kind) is bad.

Msmtp does not do queuing, it just reports an error and leaves the responsibility to deal with this error with the application that wanted to send the mail. Ideally (from the msmtp perspective), applications would handle errors and, for example, save the mail to a file instead.

However, from the application perspective, it is entirely reasonable to expect the sendmail service to never fail, and so most applications understandably do not deal with such errors.

Msmtp is (in its current form) too limited to deal with that conflict. That may be the bigger issue here. I assume that if you would prefer not to lose mail because of TLS failures, the same holds true for other (temporary or non-critical) errors that might occur in any communication over the network. So having opportunistic TLS might solve one part of the issue, but not the whole thing.

The question then is where to draw the line of what msmtp should do or be. It might be that running postfix is the better choice for your use case: you get the full reliability of an excellent mail server. Or, if you want to stay absolutely minimal, nullmailer might be an option. It seems to support queuing.

I am still not convinced that something like `tls_allow_failure on`  is a good idea. Yes, `tls_certcheck off` exists even though it is discouraged, but that does not mean we should have more options of this sort.
