### ISSUE TITLE
send-mail: /etc/msmtprc: line 16: account default was already defined

### ISSUE THREAD

**Issue by wes1993** [marlam/msmtp-mirror#32]
Hello, i have this two problem:
The first is that i use the aliases file i have this response:
![image](https://user-images.githubusercontent.com/52070589/96234392-a6ee9a80-0f99-11eb-9d3d-065cce18880d.png)

My config file:

#Set Alias
aliases /etc/aliases
#Set default values for all following accounts.
defaults
port 587
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
account gmail
host smtp.gmail.com
from stefano.pica22@gmail.com
auth on
user stefano.pica22
password <Hidden by me>
#Set a default account
account default : gmail

My Aliases File:
stefano: wes93@hotmail.it
root: wes93@hotmail.it
default: wes93@hotmail.it

The second error is that if i try to encrypt the password:
gpg -vv --encrypt -o .msmtp-gmail.gpg -r stefano.pica22@gmail.com -

![image](https://user-images.githubusercontent.com/52070589/96234869-4f046380-0f9a-11eb-88b0-b245c79d7b2a.png)

Thanks a lot
Stefano

**Comment by marlam** [comment]
The first issue: your first line is `aliases`, which is an account command. Since no account name was given explicitly yet (via an `account` command), an account named `default` is automatically created at this point. Therefore it already exists when you try to redefine it in line 16. Solution: place the `aliases` command inside your account definition, or inside the defaults section.

The second problem is unrelated to msmtp, so I cannot help.

(Please do not post screenshots of text messages, you can just copy the text instead.)

**Comment by wes1993** [comment]
Thanks a lot for you reply!! :)
I have read everywhere but I can’t find what you have written here!! :)
Now works thanks a lot :)
If you can you could add in the manual that this string must be under account definition or default section 
Really thanks a lot
Stefano
