### ISSUE TITLE
`msmtpd --command=` is equivalent to `msmtpd --command=%f`

### ISSUE THREAD

**Issue by drzraf** [marlam/msmtp-mirror#44]
It's a user mistake to run `msmtpd --command=` (no actual command) but `msmtpd` could handle it better.

Using `%f` if no command is set is:
- always wrong (Not binary named after an email address)
- not obvious (Not clear message / notification about the behavior)
- very insecure (Arbitrary command execution out of the box)

Bailing early would be preferable.

**Comment by marlam** [comment]
I [changed msmtpd](https://git.marlam.de/gitweb/?p=msmtp.git;a=blobdiff;f=src/msmtpd.c;h=fdb68b5e3c6047197b2a2645234d6ef467f521cd;hp=c4d294e9271ea0914c9ca7245ce4dc68195fdfc2;hb=a999c09684fd820a681a057cf2b4d774b0a41d3e;hpb=99f9bd74a798f7079144ebcd19bb994d6eb5a501) so that it now rejects empty arguments to command line options.
