### ISSUE TITLE
set_from_header option not working

### ISSUE THREAD

**Issue by michaelPotter** [marlam/msmtp-mirror#51]
Hi, I'm trying to set up cron to use msmtp for emails, and getting a similar error to #31, where the set_from_header isn't overriding cron's from address (which is just "root").

> May 19 05:50:53 host=smtp.fastmail.com tls=on auth=on user=me@fastmail.com from=root recipients=tome@example.com smtpstatus=504 smtpmsg='504 5.5.2 <root>: Sender address rejected: need fully-qualified address' errormsg='recipient address tome@example.com not accepted by the server' exitcode=EX_DATAERR
(notice the from=root)

My /etc/msmtprc looks like this:
```# Set default values for all following accounts.
defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log
set_from_header on

# fastmail
account        fastmail
host           smtp.fastmail.com
port           587
from           fromme@example.com
user           me@fastmail.com
password       ...


# Set a default account
account default : fastmail
```

Just to make sure I understand the option right, if `set_from_header` is set to "on", the "from" in the config should override the "from" address in this command? Right?

`echo -e 'subject:test\n\nhello' | sudo sendmail tome@example.com --from root`

**Comment by marlam** [comment]
The problem is `from=root`. This is the envelope from address, which is not necessarily the same as the one specified in any headers. You probably want to use `-f` or `--from` to set a sensible envelope from address first, and after that you can take care of the headers if necessary by using `set_from_header`.

**Comment by MAngel666** [comment]
I've the same problem with cron. I can use MAILFROM in cron but it would be nice to set it globally with msmtp. All from headers without FQDN like from=$USER should be changed to from=$USER@FQDN. It is possible with msmtp?

**Comment by marlam** [comment]
It should be possible using something like this:
```
account cron
from %U@fqdn.example
set_from_header on
```
This always sets the envelope from address to $USER@FQDN and always sets the From header accordingly. There is currently no way to detect non-FQDN From headers and replace only those.

**Comment by marlam** [comment]
The `auto_from on` overrides the previously set `from` value. I can only guess that this previous setting does not work as you intended, maybe because your host name is not what you expected. I still cannot reproduce the problem.

**Comment by RinCat** [comment]
Looks like `-f` override `set_from_header on`.
I found some programs call `sendmail` with `-f root@hostname`, and `msmtp` ignored `set_from_header on` and got `Sender address rejected: need fully-qualified address`.
Is this intended?

**Comment by marlam** [comment]
Yes, that's intended. Thank you for pointing this out. Do we need some switch to override that behavior and ignore `-f`? That might cause problems elsewhere, e.g. when automatically choosing an account.

**Comment by RinCat** [comment]
I would like have a switch to ignore `-f` value. Some programs do not support set sender, e.g. smartd. 
I think it should be done after auto choosing accounts? Like you can still set `-f`, but if the chosen account had this flag, just rewrite the sender and ignore `-f` in the final email.

**Comment by marlam** [comment]
I'm still not convinced; since this looks like a very special case, can you not just solve it by piping into a wrapper script that throws away the extra arguments and then pipes the mail directly into your application?

**Comment by RinCat** [comment]
I just give a reason why `set_from_header` not working. I do not use `auto_from`, so that is unrelated.

The use case already in the manual:

> set_from_header [(auto|on|off)]
>     When to set a From header: auto adds a From header if the mail does not have one (this is the default), on always sets a From header and overrides any existing one, and off never sets a From header.
>     If the mail server rejects the mail because its From header does not match the envelope from address (a common anti-spam measure), then you might want to set this option to on.

My email server rejects the mail because its From header does not match the user account address.
And I set `set_from_header on`, then found it still got rejected, because those daemons automatically generate a `-f username@hostname` to help identify the source, and I cannot change it.

You can think this is the same thing in https://github.com/marlam/msmtp-mirror/issues/10, but some programs use `-f` argument instead of add `From: root (Cron Daemon)` in the email header, which can also be something like `-f root` or `-f root@host` etc.

**Comment by marlam** [comment]
OK, I added a new configuration command `allow_from_override` which you can set to `off` so that the value given with the `--from` option, while potentially used to choose an account, does *not* override the envelope-from address given in the account anymore.
Can you please test this?
(It may take up to 24 hours for the change to arrive at the Github mirror, but you can always use the [main repository](https://git.marlam.de/gitweb/?p=msmtp.git).)

**Comment by RinCat** [comment]
Tested the patch on 1.8.16, and it works well. Thanks. :)

**Comment by blasto333** [comment]
I know this is closed but I am having an issue with making sure the from address is always what is in msmtp

https://stackoverflow.com/questions/73951572/msmtp-1-8-22-override-from-address-when-sending-via-php

**Comment by marlam** [comment]
The `from` in the msmtp config is the envelope from address, which is independent from the `From` header.
But yes, setting `from bob@example.com`, `set_from_header on` and `allow_from_override off` should make sure that the `From` header is always set to `From: bob@example.com`.
I'm not familiar with PHP, so I cannot guess where things go wrong. Does it work from the command line, and what does the `--debug` output say?

**Comment by rodrigoaguilera** [comment]
I got a similar error trying to send email from Drupal and it boils down to the `Sender` header that is not rewritten since is different from the `From` header it is not accepted by my SMTP provider.
I think it can be nice feature to have the same override capabilities for the `Sender` header since I believe the SMTP provider is correct in rejecting the email
