### ISSUE TITLE
Valid characters in e-mail addresses are forbidden

### ISSUE THREAD

**Issue by pboguslawski** [marlam/msmtp-mirror#61]
When trying to process message with

`MAIL FROM:<bounce-debian-security-announce=mylocalpart=my=domain@lists.debian.org>`

in msmptd 1.8.17 an error is fired

`501 Invalid address`

Such addresses are used i.e. in Debian mailinglists (example mylocalpart@my.domain subscriber).

According to

(*) https://en.wikipedia.org/wiki/Email_address#Syntax

= character is allowed in message localpart.

msmtpd should:

(1) allow any valid character (*) as in

https://github.com/marlam/msmtp-mirror/blob/master/src/msmtpd.c#L175

(2) allow user to disable address verification if user wants to process messages even with broken addresses.

**Comment by pboguslawski** [comment]
Please find patch [10-msmtpd-noverify.patch.gz](https://github.com/marlam/msmtp-mirror/files/7461670/10-msmtpd-noverify.patch.gz) for (2) that works for us,

**Comment by marlam** [comment]
I added `=` to the list of allowed characters. Allowing any character is very dangerous because the mail addresses appear on the command line of the pipe command, and therefore may be interpreted by a shell. For example, a malicious SMTP client may send something like the following:
```
RCPT TO:`/bin/chmod a+r /etc/restricted_file`
```

**Comment by pboguslawski** [comment]
> Allowing any character is very dangerous 

msmtpd should allow any valid e-mail address - adding just = is not enough - legitimate messages may be bounced if other valid chars are present; this makes msmtpd useless for professional usage.

> Allowing any character is very dangerous

Not if there is wiser filtering routine processing every message before msmtpd i.e. internal regular mail server. Consider implementing `--noverify` option as in patch above if you don't plan to correctly validate e-mail addresses in msmtpd. This is not enabled by default so won't break anything.

> the mail addresses appear on the command line

Adding address to cmd should be optional - introduces unnecessarry risks when used with procmail:

`msmtpd --command '/usr/bin/procmail -p -m /somedir/.procmailrc --'`

Consider adding another option do disable adding address to cmd for better security.

**Comment by pboguslawski** [comment]
Patch [Uploading 10-msmtpd-noverify-norecipients.patch.gz…]() introduces two arguments that allow one to use msmtpd as simple smtp to procmail filter middleware without tainted data in cmd and without bouncing legitimate email addresses:

`msmtpd --noverify --norecipients --command '/usr/bin/procmail -p -m /somedir/.procmailrc'`

**Comment by marlam** [comment]
- There are good reasons to not allow any character that the RFCs allow, see e.g. https://www.jochentopf.com/email/chars.html. For example, I don't think it is a restriction to not allow `[` or `]` even though the RFC technically allows these characters.
- It is probably a good idea to not use `popen()` but instead replicate its functionality based on some `exec*()` function to avoid involving a shell. But it's a mess to implement this correctly.

**Comment by pboguslawski** [comment]
> It is probably a good idea to not use popen()

...or pass tained data safely encoded (i.e. base64) if target cmd may be notified with extra flag to decode it before use.

**Comment by marlam** [comment]
This discussion of the implications of the pipe command line has lead to the discovery that there was a security problem, which is fixed in 1.8.19; see https://marlam.de/msmtp/news/.
My plan now is to 1) write a replacement for `popen()` that does not involve the shell (and, while I'm at it, can safely handle any output from the pipe command) and then 2) extent the set of allowed characters in mail addresses since we don't have to care about shell effects anymore.
The pipe command is assumed to implement a common sendmail-like interface, so I currently don't see the value in either encoding the mail addresses (that should not be necessary when we get rid of the shell), or in omitting the recipient addresses from the command line (since that throws away the mail envelope).

**Comment by pboguslawski** [comment]
> The pipe command is assumed to implement a common sendmail-like interface
> since that throws away the mail envelope)

With our patch one can use msmptd as simple (=no need for full mail server) smtp frontend inside container, to pass message to application that expects messages on its stdin. Envelope in this scenario may by already added (by full mail server on front) in message header or may not be required by application at all.

Consider applying our mod to make msmtpd more universal tool.

**Comment by marlam** [comment]
I'm still not convinced; since this looks like a very special case, can you not just solve it by piping into a wrapper script that throws away the extra arguments and then pipes the mail directly into your application? (I am hesitant about adding code for very special and rare use cases, even more so if those cases can be addressed in a different way.)

**Comment by pboguslawski** [comment]
> can you not just solve it by piping into a wrapper script that throws away the extra arguments and then pipes the mail directly into your application?

Wrapper script won't stop msmtpd from passing tained data in exec args (dangerous, resolved by --norecipients in our patch) nor bouncing valid e-mail addresses with chars your algo don't like (resolved by --noverify in our patch).

**Comment by marlam** [comment]
There is already a plan to solve the 'problematic data' part by avoiding the shell, and then solve the 'rejecting technically valid mail addresses' part, as outlined above. I would like to follow that plan instead, since the --norecipients option covers only a very special use case as far as I can see, and the --noverify option will not be needed anymore.

**Comment by pboguslawski** [comment]
In case you'll change your mind please find PR ready to be merged:
https://github.com/marlam/msmtp-mirror/pulls

**Comment by marlam** [comment]
I must admit that I cannot find the time to write the planned replacement for `popen`/`pclose`, which means I cannot implement the plan outlined on Nov 4.
I am still not convinced to make the changes you requested since this seems too much of a special case.
Therefore I'm closing this issue now.
Sorry, but for now it looks like you need to use a patched version of msmtpd.
